In [46]:
import numpy as np

In [47]:
import pandas as pd

In [48]:
import matplotlib.pyplot as plt

In [49]:
import seaborn as sns

In [50]:
df = pd.read_csv("C:/Users/Odunayo Grace/Desktop/Backup files/Desktop/2024 GROWTH/HAMOYE DATA SCIENCE INTERNSHIP_Must_complete/FoodBalanceSheets_E_Africa_NOFLAG.csv", encoding = "latin-1")

In [51]:
df.head()

,Area Code,Area,Item Code,Item,Element Code,Element,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
0,4,Algeria,2501,Population,511,Total Population - Both sexes,1000 persons,38924.00,39728.00,40551.00,41389.00,42228.00
1,4,Algeria,2501,Population,5301,Domestic supply quantity,1000 tonnes,0.00,0.00,0.00,0.00,0.00
2,4,Algeria,2901,Grand Total,664,Food supply (kcal/capita/day),kcal/capita/day,3377.00,3379.00,3372.00,3341.00,3322.00
3,4,Algeria,2901,Grand Total,674,Protein supply quantity (g/capita/day),g/capita/day,94.90,94.35,94.72,92.82,91.83
4,4,Algeria,2901,Grand Total,684,Fat supply quantity (g/capita/day),g/capita/day,80.06,79.36,77.40,80.19,77.28

In [52]:
#Q2
df.groupby("Item").sum()

,Area Code,Area,Item Code,Element Code,Element,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
Item,,,,,,,,,,,
"Alcohol, Non-Food",38447,AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAngo...,752497,1515090,ProductionImport QuantityStock VariationDomest...,1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...,2403.00,2180.00,2223.00,2348.00,2293.00
Alcoholic Beverages,75016,AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...,1649136,2171381,ProductionImport QuantityStock VariationExport...,1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...,102410.11,98783.72,96958.75,95581.06,97847.27
Animal Products,18060,AlgeriaAlgeriaAlgeriaAngolaAngolaAngolaBeninBe...,397035,90990,Food supply (kcal/capita/day)Protein supply qu...,kcal/capita/dayg/capita/dayg/capita/daykcal/ca...,11935.65,11811.73,11661.69,11547.65,11578.61
Animal fats,85279,AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...,1882494,2567303,ProductionImport QuantityStock VariationExport...,1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...,209460.54,200675.72,183314.22,269617.53,269648.27
Apples and products,69280,AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...,1352989,1920418,ProductionImport QuantityStock VariationExport...,1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...,9499.23,10559.15,9853.26,10198.90,9640.51
...,...,...,...,...,...,...,...,...,...,...,...
"Vegetables, Other",77779,AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...,1518715,2275409,ProductionImport QuantityStock VariationExport...,1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...,155038.96,158104.08,156218.90,157752.59,163987.21
Vegetal Products,18060,AlgeriaAlgeriaAlgeriaAngolaAngolaAngolaBeninBe...,391905,90990,Food supply (kcal/capita/day)Protein supply qu...,kcal/capita/dayg/capita/dayg/capita/daykcal/ca...,107145.19,107064.17,106792.72,107655.20,107775.39
Wheat and products,87073,AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...,1639683,2654934,ProductionImport QuantityStock VariationExport...,1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...,232670.13,234710.51,239377.07,240047.62,242645.19
Wine,66206,AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...,1319535,1818328,ProductionImport QuantityStock VariationExport...,1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...,4497.36,4251.81,3872.09,4178.02,4039.32
Yams,50798,AlgeriaAlgeriaAlgeriaAngolaAngolaAngolaAngolaB...,970905,1525745,Export QuantityDomestic supply quantityResidua...,1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...,200396.96,203151.78,220626.20,229174.59,221272.09

In [53]:
#Q3
my_data = df.groupby("Area")["Y2017"].sum()

In [54]:
my_data

Area
Algeria                         325644.27
Angola                          229159.57
Benin                           124771.22
Botswana                         22101.30
Burkina Faso                    101855.07
Cabo Verde                       14650.74
Cameroon                        232030.43
Central African Republic         29937.00
Chad                             71594.68
Comoros                             59.84
Congo                            41181.68
Côte d'Ivoire                   224599.01
Djibouti                         22729.91
Egypt                           866379.92
Eswatini                         54343.33
Ethiopia                        448683.76
Ethiopia PDR                         0.00
Gabon                            27979.64
Gambia                           23154.18
Ghana                           337599.06
Guinea                           98138.87
Guinea-Bissau                    19102.77
Kenya                           264660.66
Lesotho                          21267.96
Liberia                          29342.20
Madagascar                      131197.73
Malawi                          181098.71
Mali                            149928.33
Mauritania                      156665.46
Mauritius                        51114.83
Morocco                         388495.36
Mozambique                      161407.98
Namibia                          29874.89
Niger                           126707.58
Nigeria                        1483268.23
Rwanda                           73663.69
Sao Tome and Principe            12662.63
Senegal                          95681.15
Seychelles                         442.34
Sierra Leone                     55311.33
South Africa                    517590.54
Sudan                           239931.92
Sudan (former)                       0.00
Togo                             49841.88
Tunisia                         124167.20
Uganda                          213950.38
United Republic of Tanzania     322616.85
Zambia                          103223.77
Zimbabwe                         75919.34
Name: Y2017, dtype: float64

In [55]:
#Q4
#total number of null
total_null = df["Y2014"].isnull().sum()
total_null

1589

In [56]:
#percentage of null
total_value = len(df["Y2014"])
print(total_value)
percent_null = (total_null/total_value) * 100
print(percent_null)

60943
2.6073544131401474

In [57]:
#Q5
#df.groupby("Area")["Element"].count()

In [58]:
#Q7
df.shape

(60943, 12)

In [59]:
#Q8
#df.corr(["Y2014", "Y2015", "Y2016", "Y2017"], "Element code")

In [63]:
#Q9
df.describe()

,Area Code,Item Code,Element Code,Y2014,Y2015,Y2016,Y2017,Y2018
count,60943.000000,60943.000000,60943.000000,59354.000000,59395.000000,59408.000000,59437.000000,59507.000000
mean,134.265576,2687.176706,3814.856456,134.196282,135.235966,136.555222,140.917765,143.758381
std,72.605709,146.055739,2212.007033,1567.663696,1603.403984,1640.007194,1671.862359,1710.782658
min,4.000000,2501.000000,511.000000,-1796.000000,-3161.000000,-3225.000000,-1582.000000,-3396.000000
25%,74.000000,2562.000000,684.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,136.000000,2630.000000,5142.000000,0.090000,0.080000,0.080000,0.100000,0.070000
75%,195.000000,2775.000000,5511.000000,8.340000,8.460000,8.430000,9.000000,9.000000
max,276.000000,2961.000000,5911.000000,176405.000000,181137.000000,185960.000000,190873.000000,195875.000000

In [68]:
#Q11
my_tuppy = (1,2,5,8)
my_tuppy[2] = 6

TypeError: 'tuple' object does not support item assignment

In [66]:
#Q14 & Q20
df.groupby("Element").sum()

,Area Code,Area,Item Code,Item,Element Code,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
Element,,,,,,,,,,,
Domestic supply quantity,708993,AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...,14197445,PopulationCereals - Excluding BeerWheat and pr...,28068795,1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...,1996716.35,2021493.55,2044842.70,2088198.10,2161192.10
Export Quantity,599910,AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...,11840553,Cereals - Excluding BeerWheat and productsRice...,26026133,1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...,150020.64,157614.47,151920.46,182338.80,181594.80
Fat supply quantity (g/capita/day),675050,AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...,13535000,Grand TotalVegetal ProductsAnimal ProductsCere...,3435732,g/capita/dayg/capita/dayg/capita/dayg/capita/d...,10225.56,10235.74,10102.77,10253.84,10258.69
Feed,176272,AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...,3538507,Cereals - Excluding BeerWheat and productsRice...,7282199,1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...,216927.89,225050.22,228958.65,223705.68,233489.68
Food,663295,AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...,13285035,Cereals - Excluding BeerWheat and productsRice...,25406622,1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...,1212332.49,1232361.10,1247022.17,1258888.28,1303841.28
Food supply (kcal/capita/day),674057,AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...,13511060,Grand TotalVegetal ProductsAnimal ProductsCere...,3329296,kcal/capita/daykcal/capita/daykcal/capita/dayk...,454257.00,453383.00,451810.00,454681.00,455261.00
Food supply quantity (kg/capita/yr),658446,AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...,13185401,Cereals - Excluding BeerWheat and productsRice...,3163725,kgkgkgkgkgkgkgkgkgkgkgkgkgkgkgkgkgkgkgkgkgkgkg...,49650.63,49345.13,48985.28,48690.04,49056.85
Import Quantity,688174,AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...,13795966,Cereals - Excluding BeerWheat and productsRice...,28834929,1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...,274144.48,267018.46,286582.78,294559.09,287997.09
Losses,274353,AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...,5424803,Cereals - Excluding BeerWheat and productsRice...,10292107,1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...,153223.00,155439.00,157787.00,160614.00,163902.00
Other uses (non-food),235554,AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...,4729749,Cereals - Excluding BeerWheat and productsStar...,8926728,1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...,78718.13,66254.41,69563.68,91645.97,91300.97
Processing,271940,AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...,5350416,Cereals - Excluding BeerWheat and productsRice...,10313310,1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...,282923.00,287929.00,280631.00,292836.00,308429.00
Production,526751,AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...,10450053,Cereals - Excluding BeerWheat and productsRice...,21388191,1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...,1931287.75,1947019.39,1943537.15,2030056.89,2075072.89
Protein supply quantity (g/capita/day),675050,AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...,13535000,Grand TotalVegetal ProductsAnimal ProductsCere...,3385502,g/capita/dayg/capita/dayg/capita/dayg/capita/d...,11836.46,11833.95,11779.69,11842.45,11833.56
Residuals,623271,AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...,12421089,Cereals - Excluding BeerWheat and productsRice...,24066350,1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...,30149.00,30045.00,37224.00,35500.00,34864.00
Seed,103537,AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...,2035933,Cereals - Excluding BeerWheat and productsRice...,4211574,1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...,21922.92,23976.82,23389.20,24870.14,25263.14
Stock Variation,571566,AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...,11329527,Cereals - Excluding BeerWheat and productsRice...,21464704,1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...,58749.83,34910.99,33140.12,54316.91,20577.91
Total Population - Both sexes,6020,AlgeriaAngolaBeninBotswanaBurkina FasoCabo Ver...,112545,PopulationPopulationPopulationPopulationPopula...,22995,1000 persons1000 persons1000 persons1000 perso...,1031585.00,1058081.00,1085107.00,1112641.00,1140605.00
Tourist consumption,50308,AngolaAngolaBotswanaBotswanaBotswanaBotswanaBo...,1486528,OilcropsGroundnuts (Shelled Eq)Cereals - Exclu...,2869905,1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...,416.00,349.00,89.00,91.00,90.00

In [67]:
#unique country Q18
df["Area"].nunique()

49